/* Copyright (C) 2026 SEELE0
 * SPDX-License-Identifier: AGPL-3.0-or-later */
import type { MagiLocale } from '../i18n';

// Exact prior sections identify unedited saved defaults; do not broaden to title/prefix matching.
export const PREVIOUS_EOE_SECTIONS: Record<MagiLocale, string> = {
  "zh-CN": "## EoE：电影结尾\n\n电影在 TV 第 24 集之后展开。它与 TV 最后两集的关系存在不同解释，以下分别保留两种呈现。\n\n**25′《Air》：** 薰死后，SEELE 与源堂分别推进计划，NERV 总部遭武装入侵。美里设法让真嗣接近初号机；明日香在贰号机中重新找到与母亲的联系，一度击退敌军，最终遭量产机围攻。律子试图让 MAGI 自爆，CASPER 拒绝。\n\n**26′《真心为你》：** 绫波没有依源堂预期行动，而是与莉莉丝结合。初号机与量产机卷入第三次冲击，个体形体与意识的边界改变。真嗣在补完中重新面对人与人的痛苦和独立性；海边结尾保留开放的未来。\n",
  "zh-TW": "## EoE：電影結尾\n\n電影在 TV 第 24 集之後展開。它與 TV 最後兩集的關係存在不同解釋，以下分別保留兩種呈現。\n\n**25′《Air》：** 薰死後，SEELE 與源堂分別推進計劃，NERV 總部遭武裝入侵。美里設法讓真嗣接近初號機；明日香在貳號機中重新找到與母親的聯繫，一度擊退敵軍，最終遭量產機圍攻。律子試圖讓 MAGI 自爆，CASPER 拒絕。\n\n**26′《真心為你》：** 綾波沒有依源堂預期行動，而是與莉莉絲結合。初號機與量產機捲入第三次衝擊，個體形體與意識的邊界改變。真嗣在補完中重新面對人與人的痛苦和獨立性；海邊結尾保留開放的未來。\n",
  "en-US": "## EoE: The Film Ending\n\nThe film begins after TV episode 24. Interpretations of its relationship to the final two TV episodes differ; the two presentations remain separate here.\n\n**25′, Air:** After Kaworu's death, SEELE and Gendo advance their respective plans, and armed forces invade NERV headquarters. Misato helps Shinji reach Unit-01. Inside Unit-02, Asuka reconnects with her mother, temporarily defeats the attackers, and is eventually overwhelmed by the mass-production EVAs. Ritsuko attempts MAGI's self-destruction, but CASPER refuses.\n\n**26′, My Purest Heart for You:** Rei acts contrary to Gendo's expectations and merges with Lilith. Unit-01 and the mass-production EVAs become involved in Third Impact as boundaries of individual bodies and consciousness change. During Instrumentality, Shinji again confronts interpersonal pain and independence. The beach ending leaves the future open.\n",
  "ja-JP": "## EoE：映画の結末\n\n映画はTV第24話の後から始まります。TV最終2話との関係には異なる解釈があり、ここでは両方の表現を別々に保ちます。\n\n**25′『Air』：** カヲルの死後、SEELEとゲンドウが各自の計画を進め、NERV本部に武装勢力が侵入します。ミサトはシンジを初号機へ向かわせます。アスカは弐号機の中で母とのつながりを取り戻し、一時敵を退けますが、最終的には量産機に囲まれます。リツコはMAGIによる自爆を試み、CASPERが拒否します。\n\n**26′『まごころを、君に』：** レイはゲンドウの予想通りに行動せず、リリスと融合します。初号機と量産機はサードインパクトに巻き込まれ、個体の肉体と意識の境界が変わります。補完の中でシンジは他者との苦痛と独立性に再び向き合い、海辺の結末は未来を開かれたままにします。\n"
};

// Chinese default briefly shipped with the supplied Traditional Chinese EoE paragraphs.
export const MIXED_SCRIPT_EOE_SECTION = "## EoE：电影结尾\n\n电影在 TV 第 24 集之后展开。它与 TV 最后两集的关系存在不同解释，以下分别保留两种呈现。\n\n**25′《Air》：** 劇情承接電視版第二十四話[3]。碇真嗣因為殺了渚薰而產生罪惡感，去病房找明日香尋求慰藉，但失去意識的明日香無法回應。無助的真嗣對著明日香自慰後陷入自我厭惡。\n\n另一方面，最後的使徒（渚薰）被消滅後，SEELE為了推行自己的人類補完計畫而對碇源堂把持的NERV總部發動全面攻擊。首先操控各國以MAGI備用機試圖駭進NERV總部的MAGI一號機，但被赤木律子用666號防護程式成功阻擋。繼而挑動日本政府派遣戰略自衛隊攻入地下都市、抹殺NERV人員。 知悉人類補完計畫真相的葛城美里要求確保EVA駕駛員的人身安全，於是明日香被安置進EVA貳號機、藏匿於地底湖避難；獨自遊蕩的真嗣身陷危險境地，美里及時出現將其救出。與此同時戰略自衛隊動用n²武器和大量深水炸彈轟炸地底湖，受到攻擊而陷入恐懼的明日香確認到母親的存在後重新振作起來，操縱著貳號機接連擊毀戰略自衛隊的武器。SEELE為對付貳號機而出動九架EVA量產機。（REBIRTH篇到此結束）\n\n身受重傷的美里在臨死前鼓勵真嗣再次乘上EVA初號機，並把他送進升降機前往初號機的停機棚，但初號機被樹脂封住無法進入。碇源堂帶著綾波零抵達莉莉絲所在的終極教條區，在那等待的赤木律子試圖啟動NERV的自爆程式，但自爆決議卻被MAGI否定了，於是源堂開槍殺了她。另一方面，明日香不斷擊敗EVA量產機，眼見就要摧毀所有量產機時，貳號機被朗基努斯之槍複製品刺穿頭部後停止運作，而量產機卻悉數復活並分食貳號機。就在此時，像是回應真嗣一樣，初號機自行突破凍結，因此真嗣才終於駕駛機體出動，但映在眼前的卻是被分屍的貳號機。\n\n**26′《真心为你》：**\n碇源堂用移植了亞當的右手插入綾波零的肉體，試圖讓亞當與莉莉絲進行禁忌融合使所有靈魂合而為一，這是達到他的最終目的——與碇唯重逢的唯一手段。\n真嗣看到貳號機的屍骸後情緒當場崩潰，初號機隨即展開赤紅的十字架之翼，並喚回插在月球的朗基努斯之槍；隨後，SEELE以初號機為媒介開始人類補完的儀式，飛行中的量產機與初號機組合為卡巴拉生命樹圖案，引發第三次衝擊。此時試圖發動補完計畫的碇源堂被綾波零拒絕，綾波零吸收了碇源堂右手中的亞當並回歸莉莉絲本體；之後莉莉絲轉化為綾波的面容，並不斷變大，最終出現在真嗣面前。朗基努斯之槍插進初號機的核心，將它轉化為象徵生命胚胎的生命之樹。人類補完開始，莉莉絲以綾波的幻影出現在所有人身邊，並化成每個人最希望見到的人來引導人們，幸福滿足後的全人類還原為LCL，所有人的靈魂融入莉莉絲。真嗣在所有人合而爲一的世界中與渚薰和綾波對話時，希望「可以再見到大家」。於是補完停止，莉莉絲隨之崩解，體內的人類靈魂回歸地球。只要能靠自己的心去描繪出自己的輪廓，誰都可以回復人形。\n躺在沙灘上、回過神來的真嗣，發現周圍只有身旁的明日香。真嗣突然掐住明日香的脖子。明日香仍是面無表情地凝視著天空，並沒有反抗，反而伸出手撫摸真嗣的臉，真嗣終於哭著鬆開了手。在他哭泣的時候，明日香的目光移向他，口中只輕輕地吐出了一句話：「真噁心」[註 2]。\n";
