import i18n from 'i18next';
import LanguageDetector from 'i18next-browser-languagedetector';
import { initReactI18next } from 'react-i18next';

export const MAGI_LOCALES = ['zh-CN', 'zh-TW', 'en-US', 'ja-JP'] as const;
export type MagiLocale = typeof MAGI_LOCALES[number];
export const LANGUAGE_STORAGE_KEY = 'magi-nerv:interface-language';

export function normalizeLocale(value: string): MagiLocale {
  const language = value.trim().toLowerCase().replaceAll('_', '-');
  if (language === 'zh-tw' || language === 'zh-hk' || language === 'zh-mo' || language.includes('hant')) return 'zh-TW';
  if (language.startsWith('zh')) return 'zh-CN';
  if (language.startsWith('ja')) return 'ja-JP';
  if (language.startsWith('en')) return 'en-US';
  return 'zh-CN';
}

const resources = {
  'zh-CN': { translation: {
    connectionMode: { mock: '模拟', remote: 'API 接入' },
    connectivity: { normal: '正常', timeout: '超时', test: '测试三个节点连接', unchecked: '尚未测试，点击检查三个节点连接', simulated: '模拟节点仅检查本地连接，不代表真实 API 接入。' },
    language: { label: '界面语言', zhCN: '简体中文', zhTW: '繁體中文', en: 'English', ja: '日本語' },
    common: { close: '关闭', cancel: '取消', save: '保存', restore: '恢复默认', node: '节点{{index}}', global: '全局设定', setting: '整体设定', settingBook: '设定书', decision: '判定', history: '历史', unavailable: '不可用' },
    nav: { label: 'MAGI 主导航', status: '系统状态', language: '选择界面语言', settings: '设置', openMenu: '打开导航菜单', closeMenu: '关闭导航菜单' },
    errors: { timeout: '请求超时，请稍后重试。', cancelled: '请求已取消。', responseTooLarge: '模型响应超过允许大小。', busy: '当前有过多判定正在运行，请稍后重试。' },
    status: { connecting: '正在建立神经连接…', startupError: '启动序列已中断', online: '正常', degraded: '警戒', offline: '中断', starting: '启动中', mock: '模拟系统', remote: '外部系统', nominal: '正常', waiting: '待機', approve: '通过', reject: '否决', abstain: '弃权' },
    verdict: { pending: '等待输入', approved: '通过', rejected: '否决', review: '需要复核', pendingDetail: '等待议题数据', approvedDetail: '多数表决通过', rejectedDetail: '多数表决否决', reviewDetail: '未形成有效多数' },
    decision: { directStatus: 'MAGI 直连状态', systemParameters: 'MAGI 系统参数', personalityLayer: 'MAGI 人格层', result: '议决结果', motion: '议题：', emptySubject: '未输入', finalVerdict: '最终判定', pending: '判定中', receivingVotes: '正在接收三人格投票', failure: '信号中断 / {{code}}', interrupted: '直连已中断', retry: '可重试', matrix: 'MAGI 合议矩阵', nodeConfig: '人格节点设置', nodeHint: '点击各节点进行参数设置', activeMotion: '当前议题', currentMotion: '当前动议', agenda: '判定议题', agendaPlaceholder: '请输入要交由 MAGI 判定的议题…', advanced: '高级选项', priority: '优先级', scenario: '情景', low: '低', normal: '普通', critical: '最高', standard: '标准', rejectScenario: '否决验证', reviewScenario: '暂缓验证', execute: '开始判定', cancel: '取消判定', clear: '清除议题', subjectRequired: '请输入要提交给 MAGI 的议题。', nodeFailed: '节点执行失败，请查看历史记录。', networkError: '判定连接发生错误。', characterCount: '{{count}} / 240', waiting: '等待', layers: '人格层', requestFailed: '判定请求失败，请稍后重试。' },
    settings: { system: '系统配置', node: '节点配置', nodeName: '节点名称', nodeNameHelp: '留空恢复默认名称，最多 {{max}} 个字符。', globalTitle: '整体设定 · 连接配置', nodeTitle: '{{id}} 节点配置', close: '关闭设置', role: '角色', roleHelp: '留空恢复默认角色，最多 {{max}} 个字符。', globalHelp: '这里管理全局连接配置，作为各节点默认使用的连接参数；每个节点也可在自己的配置页中直接填写独立参数。设定书已独立保存。', connection: '连接方式', mock: '模拟', openai: 'OpenAI 兼容', local: '本地兼容', baseUrl: '服务地址', model: '模型', apiKey: 'API 密钥', showApiKey: '显示 API 密钥', hideApiKey: '隐藏 API 密钥', modelPlaceholder: '例如: gpt-6-luna/glm-5.3/deepseek-flash', apiKeyPlaceholder: 'sk-…（本地兼容服务可留空）', mockHelp: '当前使用模拟链接，判定结果随机生成，无需填写配置信息', test: '测试 AI 接入', testing: '正在测试连接…', testSuccess: '连接成功 · {{ms}} ms（完整响应耗时）', testFailed: '连接失败 · {{ms}} ms · {{message}}', mockWarning: '模拟连接不代表 AI 服务已接入。', testHelp: '使用当前连接配置发送一条简短请求；不会创建判定任务。', prompt: '角色提示词', security: '浏览器会直接连接目标服务（需要 CORS）。API 密钥只保留在页面内存，不会保存到本地存储；刷新页面后需重新输入。', configError: '请检查连接配置。', closeLabel: '关闭配置窗口', save: '保存配置', providerError: '无法连接模型服务。' },
    book: { title: '设定书', description: '设定书为所有节点提供共同背景，与连接配置分开保存，并会附加到后续的真实模型判定请求。', background: '共同背景', restore: '恢复 EVA 默认设定', close: '关闭设定书', save: '保存设定书' },
    history: { archive: '判定记录', title: '历史记录', records: '条记录', empty: '还没有判定记录', emptyHelp: '在判定页面提交议题后，投票与模型回复会保存在这里。', start: '开始首次判定', votes: '三个人格的投票', missing: '找不到指定的判定记录', missingHelp: '记录可能已删除，或链接地址不正确。', backList: '返回历史列表', back: '返回历史', final: '最终判定', dateTime: '日期与时间', response: '记录', completed: '已完成', failed: '执行失败', notStored: '本机存储不可用，记录仅保留在当前页面。', localArchive: '本机记录', recent: '最近 {{count}} 条判定记录', noRecords: '尚无历史记录。完成一次判定后会自动归档。', close: '关闭历史记录', subject: '议题', vote: '表决' },
    boot: { dialog: 'MAGI 系统启动', chooseMode: '选择主页显示模式', modeOriginal: 'MAGI 直连界面', modeModern: 'MAGI 判定主页', selectMode: '选择显示模式', keyboard: '使用上下方向键选择，按回车键确认', select: '选择', pressEnter: '按回车键确认模式', touch: '点击选项进行选择', confirm: '进入 {{mode}}', switching: '正在切换显示模式', loadingOriginal: '正在载入直连显示驱动', loadingModern: '正在载入判定主页显示驱动', mounting: '正在挂载所选界面', phasePower: '电源启动', phasePost: '开机自检', phaseMagi: '初始程序载入', phaseReady: '系统就绪', phaseMode: '选择显示模式', phaseExit: '显示驱动切换', phaseResync: '画面重新同步', phaseReveal: '载入所选界面', keyboardLock: '键盘锁：关闭', bypass: '跳过自动启动', online: '在线', waiting: '等待中', personalComputer: '个人计算机', memory: '系统内存', display: '显示适配器', terminal: '终端地址', directLink: '直连链路', established: '已建立', channel: '通道 {{index}}', systemsOnline: '三个独立系统已上线', ready: 'MAGI 系统就绪', coprocessor: '协处理器显示', executing: '执行中', ok: '正常' },
    original: { terminal: 'MAGI 直连判定终端', history: '历史记录', historyTitle: '判定历史', historyNotice: '保存在本机 · 最近 {{count}} 条判定记录', noRecords: '尚无历史记录', storageWarning: '本机存储不可用，记录仅保留在当前页面。', emptyMotion: '请输入要提交给 MAGI 的议题。', failed: 'MAGI 判定失败。请检查输入内容后重试。', networkError: '判定连接发生错误。', newMotion: '新建议题', agenda: '判定议题', execute: '执行判定', failedStatus: '信号中断。{{message}}', transitioning: '直连切换中。', deliberation: '判定进行中。正在接收三人格投票。', final: '最终判定：{{verdict}}', awaiting: '等待议题。' },
  } },
  'zh-TW': { translation: {
    connectionMode: { mock: '模擬', remote: 'API 接入' },
    connectivity: { normal: '正常', timeout: '逾時', test: '測試三個節點連線', unchecked: '尚未測試，點擊檢查三個節點連線', simulated: '模擬節點僅檢查本機連線，不代表實際 API 接入。' },
    language: { label: '介面語言', zhCN: '简体中文', zhTW: '繁體中文', en: 'English', ja: '日本語' },
    common: { close: '關閉', cancel: '取消', save: '儲存', restore: '恢復預設', node: '節點{{index}}', global: '全域設定', setting: '整體設定', settingBook: '設定書', decision: '判定', history: '歷史', unavailable: '無法使用' },
    nav: { label: 'MAGI 主導覽', status: '系統狀態', language: '選擇介面語言', settings: '設定', openMenu: '開啟導覽選單', closeMenu: '關閉導覽選單' },
    errors: { timeout: '請求逾時，請稍後重試。', cancelled: '請求已取消。', responseTooLarge: '模型回應超過允許大小。', busy: '目前有過多判定正在執行，請稍後重試。' },
    status: { connecting: '正在建立神經連線…', startupError: '啟動程序已中斷', online: '正常', degraded: '警戒', offline: '中斷', starting: '啟動中', mock: '模擬系統', remote: '外部系統', nominal: '正常', waiting: '待機', approve: '通過', reject: '否決', abstain: '棄權' },
    verdict: { pending: '等待輸入', approved: '通過', rejected: '否決', review: '需要複核', pendingDetail: '等待議題資料', approvedDetail: '多數表決通過', rejectedDetail: '多數表決否決', reviewDetail: '尚未形成有效多數' },
    decision: { directStatus: 'MAGI 直連狀態', systemParameters: 'MAGI 系統參數', personalityLayer: 'MAGI 人格層', result: '議決結果', motion: '議題：', emptySubject: '未輸入', finalVerdict: '最終判定', pending: '判定中', receivingVotes: '正在接收三人格投票', failure: '訊號中斷 / {{code}}', interrupted: '直連已中斷', retry: '可重試', matrix: 'MAGI 合議矩陣', nodeConfig: '人格節點設定', nodeHint: '點擊各節點進行參數設定', activeMotion: '目前議題', currentMotion: '目前動議', agenda: '判定議題', agendaPlaceholder: '請輸入要交由 MAGI 判定的議題…', advanced: '進階選項', priority: '優先順序', scenario: '情境', low: '低', normal: '一般', critical: '最高', standard: '標準', rejectScenario: '否決驗證', reviewScenario: '暫緩驗證', execute: '開始判定', cancel: '取消判定', clear: '清除議題', subjectRequired: '請輸入要提交給 MAGI 的議題。', nodeFailed: '節點執行失敗，請查看歷史記錄。', networkError: '判定連線發生錯誤。', characterCount: '{{count}} / 240', waiting: '等待', layers: '人格層', requestFailed: '判定請求失敗，請稍後重試。' },
    settings: { system: '系統設定', node: '節點設定', nodeName: '節點名稱', nodeNameHelp: '留空恢復預設名稱，最多 {{max}} 個字元。', globalTitle: '整體設定 · 連線配置', nodeTitle: '{{id}} 節點設定', close: '關閉設定', role: '角色', roleHelp: '留空恢復預設角色，最多 {{max}} 個字元。', globalHelp: '此處管理全域連線配置，作為各節點預設使用的連線參數；每個節點也可在自己的設定頁中直接填寫獨立參數。設定書會獨立保存。', connection: '連線方式', mock: '模擬', openai: 'OpenAI 相容', local: '本機相容', baseUrl: '服務網址', model: '模型', apiKey: 'API 金鑰', showApiKey: '顯示 API 金鑰', hideApiKey: '隱藏 API 金鑰', modelPlaceholder: '例如: gpt-6-luna/glm-5.3/deepseek-flash', apiKeyPlaceholder: 'sk-…（本機相容服務可留空）', mockHelp: '目前使用模擬連線，判定結果隨機產生，無須填寫設定資訊', test: '測試 AI 連線', testing: '正在測試連線…', testSuccess: '連線成功 · {{ms}} ms（完整回應時間）', testFailed: '連線失敗 · {{ms}} ms · {{message}}', mockWarning: '模擬連線不代表 AI 服務已接入。', testHelp: '使用目前連線配置送出一筆簡短請求；不會建立判定任務。', prompt: '角色提示詞', security: '瀏覽器會直接連線至目標服務（需要 CORS）。API 金鑰只保留在頁面記憶體，不會儲存至本機；重新整理後需再次輸入。', configError: '請檢查連線配置。', closeLabel: '關閉配置視窗', save: '儲存配置', providerError: '無法連線至模型服務。' },
    book: { title: '設定書', description: '設定書為所有節點提供共同背景，與連線配置分開保存，並會附加至後續的真實模型判定請求。', background: '共同背景', restore: '恢復 EVA 預設設定', close: '關閉設定書', save: '儲存設定書' },
    history: { archive: '判定記錄', title: '歷史記錄', records: '筆記錄', empty: '尚無判定記錄', emptyHelp: '在判定頁面提交議題後，投票與模型回覆會保存在這裡。', start: '開始首次判定', votes: '三個人格的投票', missing: '找不到指定的判定記錄', missingHelp: '記錄可能已刪除，或連結網址不正確。', backList: '返回歷史列表', back: '返回歷史', final: '最終判定', dateTime: '日期與時間', response: '記錄', completed: '已完成', failed: '執行失敗', notStored: '本機儲存無法使用，記錄僅保留於目前頁面。', localArchive: '本機記錄', recent: '最近 {{count}} 筆判定記錄', noRecords: '尚無歷史記錄。完成一次判定後會自動歸檔。', close: '關閉歷史記錄', subject: '議題', vote: '表決' },
    boot: { dialog: 'MAGI 系統啟動', chooseMode: '選擇首頁顯示模式', modeOriginal: 'MAGI 直連介面', modeModern: 'MAGI 判定首頁', selectMode: '選擇顯示模式', keyboard: '使用上下方向鍵選擇，按 Enter 確認', select: '選擇', pressEnter: '按 Enter 確認模式', touch: '點選選項進行選擇', confirm: '進入 {{mode}}', switching: '正在切換顯示模式', loadingOriginal: '正在載入直連顯示驅動', loadingModern: '正在載入判定首頁顯示驅動', mounting: '正在掛載所選介面', phasePower: '電源啟動', phasePost: '開機自我測試', phaseMagi: '初始程式載入', phaseReady: '系統就緒', phaseMode: '選擇顯示模式', phaseExit: '顯示驅動切換', phaseResync: '畫面重新同步', phaseReveal: '載入所選介面', keyboardLock: '鍵盤鎖定：關閉', bypass: '略過自動啟動', online: '線上', waiting: '等待中', personalComputer: '個人電腦', memory: '系統記憶體', display: '顯示介面卡', terminal: '終端位址', directLink: '直連鏈路', established: '已建立', channel: '通道 {{index}}', systemsOnline: '三個獨立系統已上線', ready: 'MAGI 系統就緒', coprocessor: '協處理器顯示', executing: '執行中', ok: '正常' },
    original: { terminal: 'MAGI 直連判定終端', history: '歷史記錄', historyTitle: '判定歷史', historyNotice: '儲存於本機 · 最近 {{count}} 筆判定記錄', noRecords: '尚無歷史記錄', storageWarning: '本機儲存無法使用，記錄僅保留於目前頁面。', emptyMotion: '請輸入要提交給 MAGI 的議題。', failed: 'MAGI 判定失敗。請檢查輸入內容後重試。', networkError: '判定連線發生錯誤。', newMotion: '新增議題', agenda: '判定議題', execute: '執行判定', failedStatus: '訊號中斷。{{message}}', transitioning: '直連切換中。', deliberation: '判定進行中。正在接收三人格投票。', final: '最終判定：{{verdict}}', awaiting: '等待議題。' },
  } },
  'en-US': { translation: {
    connectionMode: { mock: 'Simulation', remote: 'API access' },
    connectivity: { normal: 'Normal', timeout: 'Timeout', test: 'Test all three node connections', unchecked: 'Not tested yet. Click to check all three node connections.', simulated: 'Simulated nodes only check local connections; this does not verify live API access.' },
    language: { label: 'Interface language', zhCN: '简体中文', zhTW: '繁體中文', en: 'English', ja: '日本語' },
    common: { close: 'Close', cancel: 'Cancel', save: 'Save', restore: 'Restore defaults', node: 'Node {{index}}', global: 'Global settings', setting: 'Overall settings', settingBook: 'Setting book', decision: 'Decision', history: 'History', unavailable: 'Unavailable' },
    nav: { label: 'MAGI primary navigation', status: 'System status', language: 'Select interface language', settings: 'Settings', openMenu: 'Open navigation menu', closeMenu: 'Close navigation menu' },
    errors: { timeout: 'The request timed out. Try again later.', cancelled: 'The request was cancelled.', responseTooLarge: 'The model response exceeded the allowed size.', busy: 'Too many decisions are running. Try again later.' },
    status: { connecting: 'Establishing neural link…', startupError: 'Startup sequence interrupted', online: 'Online', degraded: 'Degraded', offline: 'Offline', starting: 'Starting', mock: 'Simulation', remote: 'Remote', nominal: 'Nominal', waiting: '待機', approve: 'Approved', reject: 'Rejected', abstain: 'Abstained' },
    verdict: { pending: 'Awaiting input', approved: 'Approved', rejected: 'Rejected', review: 'Review required', pendingDetail: 'Waiting for agenda packet', approvedDetail: 'Majority approved execution', rejectedDetail: 'Majority rejected execution', reviewDetail: 'No valid majority reached' },
    decision: { directStatus: 'MAGI direct-link status', systemParameters: 'MAGI system parameters', personalityLayer: 'MAGI personality layer', result: 'Deliberation result', motion: 'MOTION:', emptySubject: 'No input', finalVerdict: 'FINAL VERDICT', pending: 'Deliberating', receivingVotes: 'Receiving votes from three personalities', failure: 'SIGNAL FAILURE / {{code}}', interrupted: 'DIRECT LINK INTERRUPTED', retry: 'RETRY AVAILABLE', matrix: 'MAGI deliberation matrix', nodeConfig: 'Personality node settings', nodeHint: 'Click each node to configure its parameters', activeMotion: 'ACTIVE MOTION', currentMotion: 'CURRENT MOTION', agenda: 'Decision agenda', agendaPlaceholder: 'Enter an agenda for MAGI to evaluate…', advanced: 'Advanced options', priority: 'Priority', scenario: 'Scenario', low: 'Low', normal: 'Normal', critical: 'Critical', standard: 'Standard', rejectScenario: 'Rejection check', reviewScenario: 'Review check', execute: 'Run decision', cancel: 'Cancel run', clear: 'Clear agenda', subjectRequired: 'Enter an agenda to submit to MAGI.', nodeFailed: 'A node failed to run. Check the history.', networkError: 'The decision connection failed.', characterCount: '{{count}} / 240', waiting: 'Waiting', layers: 'PERSONALITY / LAYER', requestFailed: 'The decision request failed. Try again.' },
    settings: { system: 'SYSTEM CONFIGURATION', node: 'NODE CONFIGURATION', nodeName: 'Node name', nodeNameHelp: 'Leave blank to restore the default name. Up to {{max}} characters.', globalTitle: 'Overall settings · Connection', nodeTitle: '{{id}} node settings', close: 'Close settings', role: 'Role', roleHelp: 'Leave blank to restore the default role. Up to {{max}} characters.', globalHelp: 'Manage the connection settings every node uses by default. Each node can also enter its own parameters directly in its node settings. The setting book is saved separately.', connection: 'Connection mode', mock: 'Simulation', openai: 'OpenAI compatible', local: 'Local compatible', baseUrl: 'Service URL', model: 'Model', apiKey: 'API key', showApiKey: 'Show API key', hideApiKey: 'Hide API key', modelPlaceholder: 'e.g. gpt-6-luna/glm-5.3/deepseek-flash', apiKeyPlaceholder: 'sk-… (optional for local services)', mockHelp: 'A simulated connection is currently active. Decision results are generated randomly; no configuration details are required.', test: 'Test AI connection', testing: 'Testing connection…', testSuccess: 'Connected · {{ms}} ms (full response time)', testFailed: 'Connection failed · {{ms}} ms · {{message}}', mockWarning: 'Simulation mode does not indicate a live AI connection.', testHelp: 'Sends one short request using the current connection settings. No decision is created.', prompt: 'Role prompt', security: 'The browser connects directly to the provider (CORS required). API keys stay in page memory and are not saved locally; enter them again after refresh.', configError: 'Check the connection settings.', closeLabel: 'Close configuration', save: 'Save configuration', providerError: 'Could not connect to the model service.' },
    book: { title: 'Setting book', description: 'This shared background is provided to every node, stored separately from connection settings, and attached to future live model decisions.', background: 'Shared background', restore: 'Restore EVA defaults', close: 'Close setting book', save: 'Save setting book' },
    history: { archive: 'DECISION ARCHIVE', title: 'Decision history', records: 'records', empty: 'No decisions recorded yet', emptyHelp: 'Run an agenda from the decision page to save votes and full model responses here.', start: 'Start your first decision', votes: 'Votes from three personalities', missing: 'The requested decision was not found', missingHelp: 'The record may have been deleted, or the URL may be incorrect.', backList: 'Return to history list', back: 'Back to history', final: 'Final verdict', dateTime: 'Date and time', response: 'Record', completed: 'Completed', failed: 'Execution failed', notStored: 'Local storage is unavailable. Records remain on this page only.', localArchive: 'MAGI / LOCAL ARCHIVE', recent: 'Last {{count}} decision records', noRecords: 'No history yet. A decision will be archived when it completes.', close: 'Close history', subject: 'Agenda', vote: 'Vote' },
    boot: { dialog: 'MAGI system startup', chooseMode: 'Choose a home display mode', modeOriginal: 'MAGI direct-link interface', modeModern: 'MAGI decision home', selectMode: 'SELECT DISPLAY MODE', keyboard: 'Use the up and down arrows to select, then press Enter to confirm', select: 'SELECT', pressEnter: 'PRESS ENTER TO CHOOSE MODE', touch: 'Tap an option to select', confirm: 'ENTER {{mode}}', switching: 'Switching display mode', loadingOriginal: 'Loading direct-link display driver', loadingModern: 'Loading decision-home display driver', mounting: 'Mounting selected interface', phasePower: 'POWER ON', phasePost: 'POWER-ON SELF TEST', phaseMagi: 'INITIAL PROGRAM LOAD', phaseReady: 'SYSTEM READY', phaseMode: 'DISPLAY MODE SELECTION', phaseExit: 'DISPLAY DRIVER HANDOFF', phaseResync: 'VIDEO RESYNCHRONIZATION', phaseReveal: 'SELECTED INTERFACE', keyboardLock: 'KEYBOARD LOCK: OFF', bypass: 'BYPASS AUTO-IPL', online: 'ONLINE', waiting: 'WAITING', personalComputer: 'PERSONAL COMPUTER', memory: 'SYSTEM MEMORY', display: 'DISPLAY ADAPTER', terminal: 'TERMINAL ADDRESS', directLink: 'DIRECT ACCESS LINK', established: 'ESTABLISHED', channel: 'CHANNEL {{index}}', systemsOnline: 'THREE INDEPENDENT SYSTEMS ONLINE', ready: 'MAGI SYSTEM READY', coprocessor: 'COPROCESSOR DISPLAY', executing: 'EXECUTING', ok: 'OK' },
    original: { terminal: 'MAGI direct-link decision terminal', history: 'History', historyTitle: 'Decision history', historyNotice: 'Saved locally · Last {{count}} decisions', noRecords: 'No history yet', storageWarning: 'Local storage is unavailable. Records remain on this page only.', emptyMotion: 'Enter an agenda to submit to MAGI.', failed: 'MAGI decision failed. Check the agenda and try again.', networkError: 'The decision connection failed.', newMotion: 'NEW MOTION', agenda: 'AGENDA', execute: 'EXECUTE MOTION', failedStatus: 'SIGNAL FAILURE. {{message}}', transitioning: 'DIRECT LINK TRANSITIONING.', deliberation: 'DELIBERATION IN PROGRESS. Receiving votes from three personalities.', final: 'FINAL VERDICT: {{verdict}}', awaiting: 'AWAITING MOTION.' },
  } },
  'ja-JP': { translation: {
    connectionMode: { mock: '模擬', remote: 'API 接続' },
    connectivity: { normal: '正常', timeout: 'タイムアウト', test: '3ノードの接続をテスト', unchecked: '未テスト。クリックして3ノードの接続を確認', simulated: '模擬ノードはローカル接続のみ確認し、実際の API 接続は検証しません。' },
    language: { label: '表示言語', zhCN: '简体中文', zhTW: '繁體中文', en: 'English', ja: '日本語' },
    common: { close: '閉じる', cancel: 'キャンセル', save: '保存', restore: '初期設定に戻す', node: 'ノード{{index}}', global: '全体設定', setting: '全体設定', settingBook: '設定書', decision: '判定', history: '履歴', unavailable: '利用できません' },
    nav: { label: 'MAGI メインナビゲーション', status: 'システム状態', language: '表示言語を選択', settings: '設定', openMenu: 'ナビゲーションメニューを開く', closeMenu: 'ナビゲーションメニューを閉じる' },
    errors: { timeout: 'リクエストがタイムアウトしました。後でもう一度お試しください。', cancelled: 'リクエストはキャンセルされました。', responseTooLarge: 'モデル応答が許容サイズを超えています。', busy: '実行中の判定が多すぎます。後でもう一度お試しください。' },
    status: { connecting: '神経接続を確立中…', startupError: '起動シーケンスが中断されました', online: '正常', degraded: '警戒', offline: '遮断', starting: '起動中', mock: '模擬系', remote: '外部系', nominal: '正常', waiting: '待機', approve: '承認', reject: '否決', abstain: '棄権' },
    verdict: { pending: '入力待機', approved: '承認', rejected: '否決', review: '要再審', pendingDetail: '議題パケットを待機中', approvedDetail: '多数決により実行を承認', rejectedDetail: '多数決により実行を否決', reviewDetail: '有効な多数決が成立せず' },
    decision: { directStatus: 'MAGI 直結状態', systemParameters: 'MAGI システムパラメータ', personalityLayer: 'MAGI 人格レイヤー', result: '合議結果', motion: '議題：', emptySubject: '未入力', finalVerdict: '最終判定', pending: '判定中', receivingVotes: '三人格の投票を受信中', failure: '信号異常 / {{code}}', interrupted: '直結が中断されました', retry: '再試行可能', matrix: 'MAGI 合議マトリクス', nodeConfig: '人格ノード設定', nodeHint: '各ノードをクリックしてパラメータを設定', activeMotion: '現在の議題', currentMotion: '現在の議題', agenda: '判定議題', agendaPlaceholder: 'MAGI に判定させる議題を入力してください…', advanced: '詳細設定', priority: '優先度', scenario: 'シナリオ', low: '低', normal: '通常', critical: '最優先', standard: '標準', rejectScenario: '否決検証', reviewScenario: '保留検証', execute: '判定を実行', cancel: '実行を中止', clear: '議題をクリア', subjectRequired: 'MAGI に送信する議題を入力してください。', nodeFailed: 'ノードの実行に失敗しました。履歴を確認してください。', networkError: '判定回線に障害が発生しました。', characterCount: '{{count}} / 240', waiting: '待機', layers: 'PERSONALITY / LAYER', requestFailed: '判定リクエストに失敗しました。再試行してください。' },
    settings: { system: 'SYSTEM CONFIGURATION', node: 'NODE CONFIGURATION', nodeName: 'ノード名', nodeNameHelp: '空欄で既定の名前に戻ります。最大 {{max}} 文字。', globalTitle: '全体設定 · 接続設定', nodeTitle: '{{id}} ノード設定', close: '設定を閉じる', role: '役割', roleHelp: '空欄で既定の役割に戻ります。最大 {{max}} 文字。', globalHelp: 'ここでは全体の接続設定を管理します。すべてのノードの既定の接続パラメーターとして使用され、各ノードは自分の設定画面で個別のパラメーターを直接入力できます。設定書は独立して保存されます。', connection: '接続方式', mock: '模擬', openai: 'OpenAI 互換', local: 'ローカル互換', baseUrl: 'サービス URL', model: 'モデル', apiKey: 'API キー', showApiKey: 'API キーを表示', hideApiKey: 'API キーを隠す', modelPlaceholder: '例: gpt-6-luna/glm-5.3/deepseek-flash', apiKeyPlaceholder: 'sk-…（ローカル互換では省略可）', mockHelp: '現在は模擬接続を使用しています。判定結果はランダムに生成され、設定情報の入力は不要です。', test: 'AI 接続をテスト', testing: '接続をテスト中…', testSuccess: '接続成功 · {{ms}} ms（完全応答時間）', testFailed: '接続失敗 · {{ms}} ms · {{message}}', mockWarning: '模擬回線は実際の AI 接続を示しません。', testHelp: '現在の接続設定で短いリクエストを1回送信します。判定タスクは作成されません。', prompt: '役割プロンプト', security: 'ブラウザーから接続先へ直接接続します（CORS が必要です）。API キーはページ内のメモリにのみ保持され、ローカルには保存されません。再読み込み後に再入力してください。', configError: '接続設定を確認してください。', closeLabel: '設定を閉じる', save: '設定を保存', providerError: 'モデルサービスに接続できません。' },
    book: { title: '設定書', description: '設定書は全ノードに共有する背景情報です。接続設定とは別に保存され、実際のモデルによる判定リクエストに付加されます。', background: '共有背景', restore: 'EVA 初期設定に戻す', close: '設定書を閉じる', save: '設定書を保存' },
    history: { archive: 'DECISION ARCHIVE', title: '判定履歴', records: '件', empty: '判定記録はありません', emptyHelp: '判定画面で議題を実行すると、投票とモデルの応答が保存されます。', start: '最初の判定を開始', votes: '三人格の投票', missing: '指定された判定記録が見つかりません', missingHelp: '記録が削除されたか、URL が正しくない可能性があります。', backList: '履歴一覧を確認', back: '履歴に戻る', final: '最終判定', dateTime: '日時', response: '記録', completed: '完了', failed: '実行失敗', notStored: 'ローカルストレージを利用できません。記録はこのページにのみ保持されます。', localArchive: 'MAGI / ローカル記録', recent: '最近の判定記録 {{count}} 件', noRecords: '履歴はありません。判定が完了すると自動で記録されます。', close: '履歴を閉じる', subject: '議題', vote: '投票' },
    boot: { dialog: 'MAGI システム起動', chooseMode: 'ホーム画面の表示モードを選択', modeOriginal: 'MAGI 直結インターフェース', modeModern: 'MAGI 判定ホーム', selectMode: '表示モードを選択', keyboard: '上下キーで選択し、Enter キーで確定', select: '選択', pressEnter: 'Enter キーでモードを確定', touch: '項目をタップして選択', confirm: '{{mode}} に入る', switching: '表示モードを切り替え中', loadingOriginal: '直結ディスプレイドライバーを読み込み中', loadingModern: '判定ホームドライバーを読み込み中', mounting: '選択した画面をマウント中', phasePower: '電源投入', phasePost: '電源投入時自己診断', phaseMagi: '初期プログラムロード', phaseReady: 'システム準備完了', phaseMode: '表示モード選択', phaseExit: 'ディスプレイドライバー切替', phaseResync: '映像再同期', phaseReveal: '選択画面', keyboardLock: 'キーボードロック：解除', bypass: '自動起動をスキップ', online: 'オンライン', waiting: '待機中', personalComputer: 'パーソナルコンピュータ', memory: 'システムメモリ', display: 'ディスプレイアダプター', terminal: '端末アドレス', directLink: 'ダイレクトリンク', established: '確立済み', channel: 'チャンネル {{index}}', systemsOnline: '3つの独立システムがオンライン', ready: 'MAGI システム準備完了', coprocessor: 'コプロセッサー表示', executing: '実行中', ok: '正常' },
    original: { terminal: 'MAGI 直結判定ターミナル', history: '履歴', historyTitle: '判定履歴', historyNotice: 'ローカル保存 · 最近 {{count}} 件', noRecords: '履歴はありません', storageWarning: 'ローカルストレージを利用できません。記録はこのページにのみ保持されます。', emptyMotion: 'MAGI に送信する議題を入力してください。', failed: 'MAGI 判定に失敗しました。入力を確認して再試行してください。', networkError: '判定回線に障害が発生しました。', newMotion: '新しい議題', agenda: '議題', execute: '判定を実行', failedStatus: '信号異常。{{message}}', transitioning: '直結を切り替えています。', deliberation: '判定中。三人格の投票を受信しています。', final: '最終判定：{{verdict}}', awaiting: '議題入力待ち。' },
  } }
};

i18n.use(LanguageDetector).use(initReactI18next).init({
  resources,
  fallbackLng: 'en-US',
  supportedLngs: [...MAGI_LOCALES],
  load: 'currentOnly',
  detection: {
    order: ['localStorage', 'navigator'],
    lookupLocalStorage: LANGUAGE_STORAGE_KEY,
    caches: ['localStorage'],
    convertDetectedLanguage: normalizeLocale
  },
  interpolation: { escapeValue: false },
  react: { useSuspense: false },
  initAsync: false
});

function syncDocumentLanguage(locale: string) {
  document.documentElement.lang = normalizeLocale(locale);
}

if (typeof document !== 'undefined') syncDocumentLanguage(i18n.resolvedLanguage ?? i18n.language ?? 'en-US');
i18n.on('languageChanged', (locale) => {
  if (typeof document !== 'undefined') syncDocumentLanguage(locale);
});

export async function setMagiLocale(locale: MagiLocale) {
  try { localStorage.setItem(LANGUAGE_STORAGE_KEY, locale); } catch { /* Keep the selection for this session. */ }
  await i18n.changeLanguage(locale);
}

export default i18n;

// Main keeps backend execution separate from editable presentation drafts.
const backendUiCopy = {
  'zh-CN': { draftHelp: '当前设置仅保存为界面草稿，尚未同步到后端；不会用于浏览器模型调用。', test: '测试后端连接', testHelp: '检查项目后端的系统状态，不直接请求模型服务。', mockHelp: '当前为模拟配置草稿，无需填写服务信息。', security: 'API Key 仅保留在当前页面内存中，草稿不会调用模型或上传凭据。', book: '设定书目前保存为界面草稿，尚未同步到后端判定流程。' },
  'zh-TW': { draftHelp: '目前設定僅儲存為介面草稿，尚未同步至後端；不會用於瀏覽器模型呼叫。', test: '測試後端連線', testHelp: '檢查專案後端的系統狀態，不直接請求模型服務。', mockHelp: '目前為模擬設定草稿，無需填寫服務資訊。', security: 'API Key 僅保留在目前頁面記憶體中，草稿不會呼叫模型或上傳憑證。', book: '設定書目前儲存為介面草稿，尚未同步至後端判定流程。' },
  'en-US': { draftHelp: 'These settings are UI drafts and are not synced to the backend or used for browser model calls.', test: 'Test backend connection', testHelp: 'Checks the project backend status without calling a model provider directly.', mockHelp: 'This is a mock configuration draft; service details are not required.', security: 'API keys stay in page memory. Drafts do not call models or upload credentials.', book: 'The setting book is saved as a UI draft and is not yet synced to backend decisions.' },
  'ja-JP': { draftHelp: '設定は画面用の下書きとして保存され、バックエンドには未同期です。ブラウザーからモデルを呼び出すことはありません。', test: 'バックエンド接続をテスト', testHelp: 'プロジェクトのバックエンド状態を確認します。モデルサービスへ直接接続しません。', mockHelp: '模擬設定の下書きです。サービス情報の入力は不要です。', security: 'API キーはページ内メモリのみに保持されます。下書きはモデル呼び出しや認証情報の送信を行いません。', book: '設定書は画面用の下書きです。バックエンドの判定にはまだ同期されません。' }
};
for (const [locale, { book, ...settings }] of Object.entries(backendUiCopy)) {
  i18n.addResourceBundle(locale, 'translation', { settings, book: { description: book } }, true, true);
}
